server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

data:
  customers:
    file: data/customers.json
  products:
    file: data/products.json
