app:
  name: "@project.name@"
  version: "@project.version@"

spring:
  application:
    name: accenture-challenge-java
    profiles:
      active: local
logging:
  level:
    root: info

data:
  customers:
    file: src/main/resources/data/customers.json
  products:
    file: src/main/resources/data/products.json

server:
  port: 8082

